import {env} from 'cloudflare:workers';
import {identity,sameOrigin,AccessError,failure,noCache} from '@/db/access';
type Config={BROWSER_BACKEND_URL?:string;BROWSER_WS_URL?:string;SESSION_SECRET?:string;OPENAI_API_KEY?:string};
const encode=(v:Uint8Array|string)=>btoa(typeof v==='string'?v:String.fromCharCode(...v)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function token(uid:string,secret:string,scope='http',sid=''){const header=encode(JSON.stringify({alg:'HS256',typ:'JWT'}));const body=encode(JSON.stringify({sub:uid,scope,sid,exp:Math.floor(Date.now()/1000)+300}));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(header+'.'+body));return header+'.'+body+'.'+encode(new Uint8Array(signature))}
function config(){const c=env as unknown as Config;return c}
function endpoint(c:Config){
	if(!c.BROWSER_BACKEND_URL||!c.SESSION_SECRET||c.SESSION_SECRET.length<32)throw new AccessError('Agentic Browser Backend Not Connected',503);
	const u=new URL(c.BROWSER_BACKEND_URL);
	const isLocalLoopback=['localhost','127.0.0.1','[::1]'].includes(u.hostname);
	const isSecure=u.protocol==='https:'||u.protocol==='http:'&&isLocalLoopback;
	if(!isSecure||u.username||u.password)throw new AccessError('Browser backend is not configured for this environment.',503);
	return u.href.replace(/\/$/,'');
}
async function call(c:Config,uid:string,path:string,method='GET',body?:unknown){const r=await fetch(endpoint(c)+path,{method,headers:{Authorization:'Bearer '+await token(uid,c.SESSION_SECRET!),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(45000)});const d=await r.json() as any;if(!r.ok)throw new AccessError(d.error||'Browser backend request failed',r.status);return d}
export async function GET(req:Request){try{const u=await identity(),c=config(),sid=new URL(req.url).searchParams.get('sessionId');if(!sid){if(!c.BROWSER_BACKEND_URL||!c.SESSION_SECRET)return Response.json({browser:'disconnected',ai:!!c.OPENAI_API_KEY,configured:false,message:'Agentic Browser Backend Not Connected'},{headers:noCache});try{const health=await call(c,u.userId,'/health');if(health.ready!==true||health.engine!=='chromium'||health.protocol!==1)throw Error('Invalid browser backend handshake');return Response.json({browser:'connected',ai:!!c.OPENAI_API_KEY,configured:true},{headers:noCache})}catch{return Response.json({browser:'error',ai:!!c.OPENAI_API_KEY,configured:true,message:'Browser backend is configured but unreachable.'},{headers:noCache})}}if(!/^[a-zA-Z0-9-]{1,80}$/.test(sid))throw new AccessError('Invalid session',400);const session=await call(c,u.userId,'/browser/'+sid);const base=new URL(c.BROWSER_WS_URL||endpoint(c));if(base.protocol==='https:')base.protocol='wss:';if(base.protocol==='http:')base.protocol='ws:';const isLocalLoopback=['localhost','127.0.0.1','[::1]'].includes(base.hostname);if((base.protocol!=='wss:'&&!(base.protocol==='ws:'&&isLocalLoopback))||base.username||base.password)throw new AccessError('Browser frames require a secure websocket URL.',503);const t=await token(u.userId,c.SESSION_SECRET!,'stream',sid);const stream=(channel:string)=>{const url=new URL(base.href.replace(/\/$/,'')+'/browser/'+sid+'/'+channel);url.searchParams.set('token',t);return url.href};return Response.json({session,eventsUrl:stream('events'),viewUrl:stream('view')},{headers:noCache})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const u=await identity(),c=config();const raw=await req.text();if(raw.length>45000)throw new AccessError('Request too large',413);let b;try{b=JSON.parse(raw)}catch{throw new AccessError('Invalid browser request',400)}const sid=b.sessionId;if(b.operation==='create')return Response.json(await call(c,u.userId,'/browser/session','POST',b.data||{}),{headers:noCache});if(typeof sid!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(sid))throw new AccessError('Browser session required',400);const operations:Record<string,[string,string]>={close:['DELETE',''],navigate:['POST','/navigate'],click:['POST','/click'],type:['POST','/type'],scroll:['POST','/scroll'],back:['POST','/back'],forward:['POST','/forward'],refresh:['POST','/refresh'],tabs:['GET','/tabs'],newTab:['POST','/tabs'],switchTab:['POST','/active'],closeTab:['DELETE','/tabs/'+encodeURIComponent(b.data?.tabId||'')],control:['POST','/control'],mode:['POST','/mode'],snapshot:['GET','/snapshot'],key:['POST','/key'],mouse:['POST','/mouse'],resize:['POST','/resize'],permission:['POST','/permission']};const op=operations[b.operation];if(!op)throw new AccessError('Unsupported browser operation',400);return Response.json(await call(c,u.userId,'/browser/'+sid+op[1],op[0],op[0]==='GET'?undefined:b.data||{}),{headers:noCache})}catch(e){return failure(e)}}
